### ISSUE TITLE
Render ”Loading….” while data is fetched from api

### ISSUE THREAD

**Issue by qvarnstr0m** [qvarnstr0m/GittyUp#2]

**Comment by s-k-zaman** [comment]
Thank You. This was my first contribution to GitHub.
Can I work on the error-handling issue?

**Comment by qvarnstr0m** [comment]
Alright, good job 👍 Someone else started working on the error handling so I cant assign you that, but I will open up more issues so check back soon, thanks again!

**Comment by s-k-zaman** [comment]
it's ok. but I Have already created a PR on the error-handling issue, check it out or Delete it. thanks.
